name: flutter_blue_plus_example
description: Demonstrates how to use the flutter_blue_plus plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.20.4
  flutter_riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1

flutter:
  uses-material-design: true
dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.4
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.2
